# Site settings
title: Adventure On
description: "Adventure On"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blogv1.ktan.me/" # the base hostname & protocol for your site
permalink: /:title/
paginate: 10
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
